services:
  steam-api:
    build:
      context: .
    image: aspirinna/steam-api:local
    container_name: aspirinna-steam-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 127.0.0.1:8788:8788
    volumes:
      - steam-api-data:/data

volumes:
  steam-api-data:
